### ISSUE TITLE
Problema nella funzione get_tweets

### ISSUE THREAD

**Issue by redfalcoon** [bocchilorenzo/ntscraper#2]
Buongiorno,
 utilizzando gli ottimi sviluppi da lei realizzati di ntscraper ricevo i seguentei errori:

user_tweets = scraper.get_tweets(user, mode='user', number=posts, instance="https://nitter.it")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/ntscraper/nitter.py", line 572, in get_tweets
    return self.__search(term, mode, number, since, until, max_retries, instance)
  File "/usr/local/lib/python3.6/site-packages/ntscraper/nitter.py", line 491, in __search
    to_append = self.__extract_tweet(tweet, is_encrypted)
  File "/usr/local/lib/python3.6/site-packages/ntscraper/nitter.py", line 409, in __extract_tweet
    if quoted_tweet
  File "/usr/local/lib/python3.6/site-packages/ntscraper/nitter.py", line 345, in __get_tweet_link
    return "https://twitter.com" + tweet.find("a")["href"]
TypeError: 'NoneType' object is not subscriptable

oppure

  File "/usr/local/lib/python3.6/site-packages/ntscraper/nitter.py", line 572, in get_tweets
    return self.__search(term, mode, number, since, until, max_retries, instance)
  File "/usr/local/lib/python3.6/site-packages/ntscraper/nitter.py", line 491, in __search
    to_append = self.__extract_tweet(tweet, is_encrypted)
  File "/usr/local/lib/python3.6/site-packages/ntscraper/nitter.py", line 409, in __extract_tweet
    if quoted_tweet
  File "/usr/local/lib/python3.6/site-packages/ntscraper/nitter.py", line 335, in __get_tweet_text
    else tweet.find("div", class_="quote-text").text.strip().replace("\n", " ")
AttributeError: 'NoneType' object has no attribute 'text'

nella richiesta che genera il primo errore user='romafaschifo' e posts=70. (Facendo tentativi con post < 70 non si hanno errori.)
nella richiesta che genera il secondo errore user='romaesaurito' e posts=10
con altri utenti l'errore non appare
la versione installata è quella ora disponibile su Github.
Grazie
Saluti

**Comment by bocchilorenzo** [comment]
Buongiorno,
il bug è stato sistemato, la invito a scaricare la nuova versione. L'errore che viene generato per l'utente 'romaesaurito' accade perché l'utente apparentemente non esiste e non viene trovato da nessuna istanza di Nitter.

**Comment by redfalcoon** [comment]
Buongiorno,
grazie per l'intervento di risoluzione per il primo dei due casi, come giustamente indicato romaesaurito non esiste infatti è romanoesaurito e se si prova a fare uno scraping si ottiene l'errore che segue

Traceback (most recent call last):
  chiamata user_tweets = scraper.get_tweets(user, mode='user', number=posts, instance="https://nitter.it")
  File "/usr/local/lib/python3.6/site-packages/ntscraper/nitter.py", line 574, in get_tweets
    return self.__search(term, mode, number, since, until, max_retries, instance)
  File "/usr/local/lib/python3.6/site-packages/ntscraper/nitter.py", line 494, in __search
    to_append = self.__extract_tweet(tweet, is_encrypted)
  File "/usr/local/lib/python3.6/site-packages/ntscraper/nitter.py", line 412, in __extract_tweet
    if quoted_tweet
  File "/usr/local/lib/python3.6/site-packages/ntscraper/nitter.py", line 335, in __get_tweet_text
    else tweet.find("div", class_="quote-text").text.strip().replace("\n", " ")
AttributeError: 'NoneType' object has no attribute 'text'


anche con la nuova versione del sw.
Grazie

**Comment by bocchilorenzo** [comment]
L'ultimo fix ha sistemato il bug. La re-invito a scaricare l'ultima versione.

**Comment by redfalcoon** [comment]
La ringrazio, veramente efficace e gentile. 
Volevo approfittare per segnalare che da qualche giorno le istanze nitter rispondono anche alla richiesta di hashtag e term fornendo risultato, i test fatti con ntscraper in merito sono veramente confortanti..
