### ISSUE TITLE
Empty profile should return None and not x retries

### ISSUE THREAD

**Issue by MadAim123** [bocchilorenzo/ntscraper#22]
Why it do not only return None on "Empty profile"? If there is no tweet for the searchterm, it's always empty. It tries 5 times to get another instance. But when it's empty, there is no need to try another instance? This finally (for more searchterms without tweets) ends with `High number of retries detected. Testing all instances...` and after all in an error for ip-blocking => empty instance-list:

The very final end is:
```
IndexError: list index out of range Traceback (most recent call last): 
File "/venv/lib/python3.10/site-packages/ntscraper/nitter.py", line 751, in get_tweets return self._search( 
File "/venv/lib/python3.10/site-packages/ntscraper/nitter.py", line 640, in _search soup = self._get_page(endpoint, max_retries) 
File "/venv/lib/python3.10/site-packages/ntscraper/nitter.py", line 204, in _get_page self._get_new_instance(f"Empty profile on {self.instance}") 
File "/venv/lib/python3.10/site-packages/ntscraper/nitter.py", line 153, in _get_new_instance instance = self.get_random_instance() 
File "/venv/lib/python3.10/site-packages/ntscraper/nitter.py", line 724, in get_random_instance return random.choice(self.working_instances) 
File "/usr/local/python3.10.8/lib/python3.10/random.py", line 378, in choice return seq[self._randbelow(len(seq))]
IndexError: list index out of range
```

edit: ... and sorry for all the issues. You are doing a great job! 👍

**Comment by bocchilorenzo** [comment]
The reason for retrying on empty profile is that, during my tests, I found some out-of-date instances which would sometimes show no tweets, even though the page contains tweets on the updated instances. So it's mostly a safeguard for that. I will add a parameter to avoid jumping instances if it detects an empty profile, so that it won't do this anymore if you trust the current instance.
And no need to excuse, the issues benefit everyone. Thanks for the compliment!
