### ISSUE TITLE
Only can get five tweets!

### ISSUE THREAD

**Issue by Fa5g** [bocchilorenzo/ntscraper#8]
I've tested this package and couldn't get more than five tweets despite using "since:2023-07-26" in the search string.
Is there a bug or is it related to twitter limits?

from ntscraper import Nitter

scraper = Nitter(log_level=1)
random_instance = scraper.get_random_instance()
tws=scraper.get_tweets("traffic since:2023-07-26", mode='hashtag')
for tw in tws:
	print(tw["text"])

### **Output:**
27-Jul-23 20:10:49 - No instance specified, using random instance https://nitter.kling.gg
Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "/home/fa5g/twbatch/venv/lib/python3.9/site-packages/ntscraper/nitter.py", line 582, in get_tweets
    return self.__search(term, mode, number, since, until, max_retries, instance)
  File "/home/fa5g/twbatch/venv/lib/python3.9/site-packages/ntscraper/nitter.py", line 492, in __search
    is_encrypted = self.__is_instance_encrypted(instance)
  File "/home/fa5g/twbatch/venv/lib/python3.9/site-packages/ntscraper/nitter.py", line 43, in __is_instance_encrypted
    instance_new, soup = self.__get_page("/x", instance)
  File "/home/fa5g/twbatch/venv/lib/python3.9/site-packages/ntscraper/nitter.py", line 113, in __get_page
    if soup.find_all("div", class_="show-more")[-1].find("a").text == "Load newest":
IndexError: list index out of range

Something wrong happens?

**Comment by bocchilorenzo** [comment]
To use the "since" option, it should be included as a parameter to the function. So, your call to get_tweets should become:
`tws=scraper.get_tweets("traffic", mode='hashtag', since="2023-07-26")`
